[package]
name = "seq_ex"
version = "0.1.0"
authors = ["Monica Moniot"]
edition = "2021"

[lib]
name = "seq_ex"
path = "src/lib.rs"
doc = true

[features]
default = ["std"]
std = ["futex"]

[dependencies]
futex = {version = "0.1.3", optional = true}
